{"results": {"unittest.loader.ModuleImportFailure": {"errors": {"unittest.loader.ModuleImportFailure.test_pep8": {"message": "Failed to import test module: test_pep8\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/ahmadans/a1p2/test_pep8.py\", line 3, in <module>\n    import a1\n  File \"/home/a08test/submissions/ahmadans/a1p2/a1.py\", line 102\n    if(self.dimension_checker(i=i, j=j)):\n    ^\nIndentationError: unexpected indent\n", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_pep8\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/ahmadans/a1p2/test_pep8.py\", line 3, in <module>\n    import a1\n  File \"/home/a08test/submissions/ahmadans/a1p2/a1.py\", line 102\n    if(self.dimension_checker(i=i, j=j)):\n    ^\nIndentationError: unexpected indent\n\n"}, "unittest.loader.ModuleImportFailure.test_a1": {"message": "Failed to import test module: test_a1\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/ahmadans/a1p2/test_a1.py\", line 5, in <module>\n    import a1\n  File \"/home/a08test/submissions/ahmadans/a1p2/a1.py\", line 102\n    if(self.dimension_checker(i=i, j=j)):\n    ^\nIndentationError: unexpected indent\n", "description": "", "details": "Traceback (most recent call last):\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 58, in testPartExecutor\n    yield\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/case.py\", line 577, in run\n    testMethod()\n\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 32, in testFailure\n    raise exception\n\nImportError: Failed to import test module: test_a1\nTraceback (most recent call last):\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 312, in _find_tests\n    module = self._get_module_from_name(name)\n  File \"/usr/local/cms/python-3.4.2/lib/python3.4/unittest/loader.py\", line 290, in _get_module_from_name\n    __import__(name)\n  File \"/home/a08test/submissions/ahmadans/a1p2/test_a1.py\", line 5, in <module>\n    import a1\n  File \"/home/a08test/submissions/ahmadans/a1p2/a1.py\", line 102\n    if(self.dimension_checker(i=i, j=j)):\n    ^\nIndentationError: unexpected indent\n\n"}}}}, "origin": "/home/a08test/submissions/ahmadans/a1p2", "students": [{"student_id": "ahmadans", "email": "ansaf.ahmad@mail.utoronto.ca", "last": "Ahmad", "source": "N/A", "first": "Ansaf", "student_number": "0000000000", "section": "N/A"}], "assignment": "a1p2", "date": "2016-03-12T23:59:30"}